/* Eラーニング用カタログ定数。将来 API 化するまでのローカルデータ層。 */
export const LearningCatalog = [
  { id: "el-java-basic",  title: "Java基礎",           category: "プログラミング", color: "#DC2626",
    skills: ["Java", "オブジェクト指向", "コレクション", "例外処理"],
    lessons: 12, duration: "6", level: "入門",
    desc: "Javaの基礎文法からオブジェクト指向プログラミングまでを習得します。" },
  { id: "el-aws-basic",   title: "AWS基礎",             category: "クラウド",       color: "#D97706",
    skills: ["AWS", "クラウド", "IAM", "S3", "EC2"],
    lessons: 8,  duration: "4", level: "入門",
    desc: "AWSの主要サービスと基礎概念を学び、クラウドインフラの基礎を理解します。" },
  { id: "el-spring-boot", title: "Spring Boot",        category: "プログラミング", color: "#16A34A",
    skills: ["Spring Boot", "REST API", "DI/IoC", "JPA"],
    lessons: 10, duration: "5", level: "中級",
    desc: "Spring BootでWebアプリケーション開発とREST API設計を習得します。" },
  { id: "el-react",       title: "React",               category: "フロントエンド", color: "#2563EB",
    skills: ["React", "JavaScript", "JSX", "Hooks"],
    lessons: 10, duration: "5", level: "中級",
    desc: "ReactによるモダンなフロントエンドUI開発を習得します。" },
  { id: "el-biz-manner",  title: "ビジネスマナー",      category: "ビジネス",       color: "#7C3AED",
    skills: ["ビジネスマナー", "コミュニケーション", "報連相", "メール作成"],
    lessons: 6,  duration: "3", level: "入門",
    desc: "社会人基礎力とビジネスマナーを身につけます。" },
  { id: "el-ai-basic",    title: "AI基礎",              category: "AI",             color: "#0891B2",
    skills: ["AI", "機械学習", "プロンプトエンジニアリング", "生成AI活用"],
    lessons: 8,  duration: "4", level: "入門",
    desc: "AIの基礎概念と実業務への活用方法を学びます。" },
  { id: "el-git",         title: "Git・バージョン管理",  category: "ツール",         color: "#374151",
    skills: ["Git", "GitHub", "バージョン管理", "ブランチ戦略"],
    lessons: 6,  duration: "3", level: "入門",
    desc: "Gitによるソース管理とGitHubを使ったチーム開発を学びます。" },
  { id: "el-sql",         title: "SQL・データベース",    category: "データベース",   color: "#0284C7",
    skills: ["SQL", "データベース設計", "正規化", "インデックス"],
    lessons: 8,  duration: "4", level: "入門",
    desc: "SQLの基礎から実践的なデータベース設計を習得します。" },
];

// レッスンカタログ（将来 GET /courses/{id}/lessons へ差し替え可能）
export const LESSON_CATALOG = {
  "el-java-basic": [
    { id: "el-java-basic-l1", title: "このコースで学ぶこと", type: "text", duration: "5分",
      summary: "Javaと本コースの全体像を把握します。",
      points: ["Javaの特徴（Write Once, Run Anywhere）", "学習ロードマップの確認", "開発環境の概要"],
      body: "Javaは世界で最も広く使われるオブジェクト指向言語の一つです。本コースでは変数・制御構造・オブジェクト指向を段階的に習得します。実務で通用するJavaの基礎を、この一つのコースで体系的に身につけましょう。" },
    { id: "el-java-basic-l2", title: "変数・データ型・配列", type: "video", duration: "20分",
      summary: "Javaの基本データ型と配列の使い方を学びます。",
      points: ["int / String / boolean 等の基本型", "変数の宣言と初期化", "配列の生成と操作"] },
    { id: "el-java-basic-l3", title: "条件分岐と反復処理", type: "video", duration: "20分",
      summary: "if/switch・for/while で制御フローを学びます。",
      points: ["if-else / switch 構文", "for / while / do-while ループ", "break / continue の使い方"] },
    { id: "el-java-basic-l4", title: "オブジェクト指向基礎", type: "text", duration: "15分",
      summary: "クラス・継承・ポリモーフィズムを理解します。",
      points: ["クラスとインスタンスの違い", "カプセル化・継承・多態性の3原則", "インターフェースと抽象クラス"],
      body: "OOPの核心は「カプセル化・継承・多態性」の3原則です。クラスを設計図、オブジェクトをその実体と考え、再利用性の高いコードを書きましょう。継承で共通機能を親クラスに集約し、インターフェースで契約を定義します。" },
    { id: "el-java-basic-l5", title: "確認テスト", type: "quiz", duration: "10分",
      summary: "Java基礎の理解を確認します。",
      questions: [
        { id: "q1", q: "Javaのオブジェクト指向3大要素として正しいものは？", options: ["カプセル化・継承・多態性", "変数・配列・メソッド", "クラス・構造体・共用体", "if・for・while"], answer: 0 },
        { id: "q2", q: "整数を扱うJavaの基本データ型は？", options: ["string", "boolean", "int", "float64"], answer: 2 },
        { id: "q3", q: "クラスからオブジェクトを生成するキーワードは？", options: ["create", "new", "make", "init"], answer: 1 },
      ] },
  ],
  "el-aws-basic": [
    { id: "el-aws-basic-l1", title: "クラウドとAWSの概要", type: "text", duration: "10分",
      summary: "クラウドコンピューティングとAWSの基本を理解します。",
      points: ["オンプレミスとクラウドの違い", "IaaS / PaaS / SaaS の分類", "AWSの主要リージョンとサービス"],
      body: "AWSはAmazonが提供する世界最大のクラウドプラットフォームです。初期投資なしに必要なリソースを必要な分だけ使える「従量課金」が最大の特徴です。200以上のサービスを組み合わせてシステムを構築します。" },
    { id: "el-aws-basic-l2", title: "IAM・S3入門", type: "video", duration: "20分",
      summary: "IAMによるアクセス制御とS3のオブジェクトストレージを学びます。",
      points: ["IAMユーザー・グループ・ポリシーの構成", "最小権限の原則", "S3バケット作成とオブジェクト操作"] },
    { id: "el-aws-basic-l3", title: "EC2・VPC基礎", type: "video", duration: "25分",
      summary: "仮想サーバーEC2とネットワーク設計VPCを学びます。",
      points: ["EC2インスタンスタイプと起動手順", "セキュリティグループの設定", "VPCとサブネット・ルーティング"] },
    { id: "el-aws-basic-l4", title: "確認テスト", type: "quiz", duration: "10分",
      summary: "AWS基礎の理解を確認します。",
      questions: [
        { id: "q1", q: "AWSのIAMの主な役割は？", options: ["データベース管理", "アクセス権限の管理", "ネットワーク監視", "コスト計算"], answer: 1 },
        { id: "q2", q: "S3はどの種類のストレージ？", options: ["ブロックストレージ", "ファイルストレージ", "オブジェクトストレージ", "インメモリ"], answer: 2 },
        { id: "q3", q: "EC2はどんなサービス？", options: ["メール配信", "DNS管理", "仮想サーバー", "CDN"], answer: 2 },
      ] },
  ],
  "el-spring-boot": [
    { id: "el-spring-boot-l1", title: "Spring Bootとは", type: "text", duration: "8分",
      summary: "Spring Bootの特徴と従来Springとの違いを理解します。",
      points: ["Convention over Configuration（設定より規約）", "組み込みTomcatで即起動", "Auto-configurationの仕組み"],
      body: "Spring Bootは、Javaの定番フレームワークSpringを簡単に使えるようにしたプロジェクトです。複雑なXML設定が不要で、アノテーションだけで本格的なWebアプリが構築できます。REST APIサーバー、バッチ処理、マイクロサービスなど幅広いユースケースに対応しています。" },
    { id: "el-spring-boot-l2", title: "REST API開発", type: "video", duration: "25分",
      summary: "@RestControllerを使ったREST APIの実装を学びます。",
      points: ["@RestController / @GetMapping / @PostMapping", "@RequestBody / @PathVariable", "ResponseEntityでのステータス制御"] },
    { id: "el-spring-boot-l3", title: "DI・JPA入門", type: "video", duration: "20分",
      summary: "依存性注入とSpring Data JPAによるDB操作を学びます。",
      points: ["@Autowired / @Service / @Repository の使い方", "JpaRepositoryのCRUD操作", "エンティティとテーブルのマッピング"] },
    { id: "el-spring-boot-l4", title: "確認テスト", type: "quiz", duration: "10分",
      summary: "Spring Bootの理解を確認します。",
      questions: [
        { id: "q1", q: "DIとは何の略？", options: ["Data Integration", "Dependency Injection", "Dynamic Interface", "Direct Import"], answer: 1 },
        { id: "q2", q: "@RestControllerの役割は？", options: ["DB接続", "REST APIエンドポイント定義", "スケジュール実行", "認証処理"], answer: 1 },
        { id: "q3", q: "Spring Data JPAが提供するCRUD用インターフェースは？", options: ["CrudRepository / JpaRepository", "DatabaseManager", "EntityManagerのみ", "SQLクラス"], answer: 0 },
      ] },
  ],
  "el-react": [
    { id: "el-react-l1", title: "Reactの基礎概念", type: "text", duration: "8分",
      summary: "コンポーネントベースUIの考え方を理解します。",
      points: ["コンポーネント = UIの再利用可能な部品", "仮想DOM（Virtual DOM）の仕組み", "単方向データフローの原則"],
      body: "ReactはMetaのJavaScriptライブラリです。UIをコンポーネントの組み合わせとして設計し、仮想DOMにより必要な部分だけを効率よく更新します。一度習得すれば、ReactNativeでモバイルアプリも作れます。" },
    { id: "el-react-l2", title: "コンポーネントとJSX", type: "video", duration: "20分",
      summary: "JSX記法と関数コンポーネントの書き方を習得します。",
      points: ["JSX = JavaScript + HTMLライクな構文", "関数コンポーネントの作成", "propsによるデータの受け渡し"] },
    { id: "el-react-l3", title: "Hooks入門（useState / useEffect）", type: "video", duration: "20分",
      summary: "状態管理と副作用処理の基本を学びます。",
      points: ["useStateでコンポーネント状態を管理", "useEffectで副作用を実行", "依存配列の正しい使い方"] },
    { id: "el-react-l4", title: "確認テスト", type: "quiz", duration: "10分",
      summary: "Reactの理解を確認します。",
      questions: [
        { id: "q1", q: "useStateの役割は？", options: ["APIを呼び出す", "コンポーネントの状態を管理する", "CSSを適用する", "ルーティングを設定する"], answer: 1 },
        { id: "q2", q: "JSXとは？", options: ["JavaとXMLの組み合わせ", "JavaScriptにHTMLライクな構文を組み込む書き方", "JSONの拡張形式", "CSSフレームワーク"], answer: 1 },
        { id: "q3", q: "useEffectの依存配列に[]を渡すと？", options: ["毎回レンダー時に実行", "マウント時に1回だけ実行", "実行されない", "エラーになる"], answer: 1 },
      ] },
  ],
  "el-biz-manner": [
    { id: "el-biz-manner-l1", title: "社会人マインドセット", type: "text", duration: "8分",
      summary: "学生から社会人への意識転換を理解します。",
      points: ["自律・責任・貢献の意識", "時間管理と約束の厳守", "ビジネスにおける信頼構築"],
      body: "社会人として最も大切なのは「責任感」です。締め切りを守る、連絡を怠らない、言動に責任を持つ——この基本姿勢がすべての土台になります。学生時代の感覚から早く切り替えることが、成長の第一歩です。" },
    { id: "el-biz-manner-l2", title: "挨拶・敬語・電話対応", type: "video", duration: "15分",
      summary: "正しい挨拶・敬語・電話の受け方を学びます。",
      points: ["挨拶の基本と礼の種類", "尊敬語・謙譲語・丁寧語の使い分け", "電話応対のマナーと流れ"] },
    { id: "el-biz-manner-l3", title: "報連相・メール作成", type: "video", duration: "15分",
      summary: "報連相の実践とビジネスメールの書き方を習得します。",
      points: ["報告のタイミングと伝え方", "メールの件名・本文・結語の構成", "CC/BCCの使い分けと注意点"] },
    { id: "el-biz-manner-l4", title: "確認テスト", type: "quiz", duration: "8分",
      summary: "ビジネスマナーの理解を確認します。",
      questions: [
        { id: "q1", q: "「報連相」の「報」とは？", options: ["報告", "連絡", "相談", "報酬"], answer: 0 },
        { id: "q2", q: "ビジネスメールの件名として適切なものは？", options: ["お世話になります", "【確認依頼】〇〇資料送付の件", "こんにちは", "よろしくお願いします"], answer: 1 },
        { id: "q3", q: "電話を受けた際、最初に伝えることは？", options: ["相手の名前", "自社名と自分の名前", "折り返し先の番号", "担当者の不在"], answer: 1 },
      ] },
  ],
  "el-ai-basic": [
    { id: "el-ai-basic-l1", title: "AIとは何か", type: "text", duration: "8分",
      summary: "AIの歴史と種類、生成AIブームを概観します。",
      points: ["AIの定義と種類（弱いAI・強いAI）", "機械学習・深層学習の位置づけ", "生成AIと従来型AIの違い"],
      body: "人工知能（AI）とは人間の知的活動をコンピュータで再現する技術です。現在の主流は機械学習で、大量のデータからパターンを学習します。ChatGPT等の生成AIは、その応用としてテキスト・画像等を自動生成でき、実務への活用が急速に広がっています。" },
    { id: "el-ai-basic-l2", title: "機械学習の基礎", type: "video", duration: "20分",
      summary: "教師あり・なし・強化学習の概念を理解します。",
      points: ["教師あり学習（分類・回帰）", "教師なし学習（クラスタリング）", "ニューラルネットワークの仕組み"] },
    { id: "el-ai-basic-l3", title: "プロンプトエンジニアリングと活用", type: "video", duration: "20分",
      summary: "生成AIを実務で活用するプロンプト設計を学びます。",
      points: ["良いプロンプトの構成要素", "ゼロショット・フューショット学習", "業務活用事例（コード生成・文書作成）"] },
    { id: "el-ai-basic-l4", title: "確認テスト", type: "quiz", duration: "10分",
      summary: "AI基礎の理解を確認します。",
      questions: [
        { id: "q1", q: "「教師あり学習」の特徴は？", options: ["ラベルなしデータで学習", "ラベル付きデータで正解を学習", "試行錯誤で最適行動を学ぶ", "人間が全ルールを定義"], answer: 1 },
        { id: "q2", q: "プロンプトエンジニアリングとは？", options: ["AIモデルの学習データ作成", "AIへの指示文を最適化すること", "AIシステムを構築すること", "MLアルゴリズムの開発"], answer: 1 },
        { id: "q3", q: "生成AIが生成できないものは？", options: ["テキスト文章", "プログラムコード", "物理的な商品", "画像・音楽"], answer: 2 },
      ] },
  ],
  "el-git": [
    { id: "el-git-l1", title: "バージョン管理とGitの基礎", type: "text", duration: "5分",
      summary: "バージョン管理の必要性とGitの基本概念を理解します。",
      points: ["バージョン管理がない世界の問題", "分散型バージョン管理の利点", "リポジトリ・コミット・ブランチの概念"],
      body: "バージョン管理とはファイルの変更履歴を記録するシステムです。Gitは世界で最も広く使われる分散型バージョン管理システムで、「いつ・誰が・何を変更したか」を追跡でき、過去の状態への巻き戻しが可能です。" },
    { id: "el-git-l2", title: "Gitの基本操作", type: "video", duration: "20分",
      summary: "init・add・commit・push・pullなどの基本コマンドを習得します。",
      points: ["git init / git clone", "git add / git commit", "git push / git pull / git fetch"] },
    { id: "el-git-l3", title: "GitHubとブランチ戦略", type: "video", duration: "15分",
      summary: "GitHubを使ったチーム開発とブランチ管理を学びます。",
      points: ["Pull Requestとコードレビュー", "Git Flowとトランクベース開発", "コンフリクトの解決方法"] },
    { id: "el-git-l4", title: "確認テスト", type: "quiz", duration: "8分",
      summary: "Gitの理解を確認します。",
      questions: [
        { id: "q1", q: "git commitの役割は？", options: ["変更をリモートに送信", "変更をローカルリポジトリに記録", "ブランチを切り替え", "ファイルを削除"], answer: 1 },
        { id: "q2", q: "git pushの役割は？", options: ["ローカルをリモートに送信", "リモートをローカルに取得", "ブランチを作成", "履歴を確認"], answer: 0 },
        { id: "q3", q: "Gitのブランチの目的は？", options: ["ファイルを圧縮", "独立した開発作業を並行して進める", "リモートサーバーに接続", "コードの文法チェック"], answer: 1 },
      ] },
  ],
  "el-sql": [
    { id: "el-sql-l1", title: "データベース基礎", type: "text", duration: "8分",
      summary: "リレーショナルDBの基本概念とSQLの役割を理解します。",
      points: ["テーブル・行・列の概念", "主キー・外部キー・インデックス", "RDBMSの種類（MySQL・PostgreSQL等）"],
      body: "データベースとはデータを効率的に保存・管理・検索するシステムです。リレーショナルDB（RDB）はデータを表の形で管理し、SQL（Structured Query Language）で操作します。エンジニアなら必須のスキルです。" },
    { id: "el-sql-l2", title: "SELECT文・WHERE・JOIN", type: "video", duration: "25分",
      summary: "データ取得の基本文法とテーブル結合を習得します。",
      points: ["SELECT / FROM / WHERE の基本", "ORDER BY / GROUP BY / HAVING", "INNER JOIN / LEFT JOIN による結合"] },
    { id: "el-sql-l3", title: "テーブル設計と正規化", type: "text", duration: "15分",
      summary: "良いテーブル設計の原則と正規化を学びます。",
      points: ["第1・第2・第3正規形の意味", "ER図の読み書き", "インデックス設計の基本"],
      body: "正規化とはデータの重複を排除し一貫性を保つ設計技法です。第1→第2→第3正規形の順に適用します。ただし過度な正規化はJOINが複雑になるため、実務ではバランスが重要です。" },
    { id: "el-sql-l4", title: "確認テスト", type: "quiz", duration: "10分",
      summary: "SQLの理解を確認します。",
      questions: [
        { id: "q1", q: "テーブルから特定の列を取得するSQLは？", options: ["GET name FROM users", "SELECT name FROM users", "FETCH name FROM users", "READ name FROM users"], answer: 1 },
        { id: "q2", q: "2つのテーブルを結合するキーワードは？", options: ["MERGE", "CONNECT", "JOIN", "LINK"], answer: 2 },
        { id: "q3", q: "データベース正規化の主な目的は？", options: ["クエリを高速化", "データの重複排除と一貫性確保", "テーブル数を増やす", "インデックスを削除"], answer: 1 },
      ] },
  ],
};

